enabled is a flag to enable Hazelcast application
hazelcast/charts pull request #168
Opened 2020-10-28 13:37 UTC by jisnardo

PR for deploy hazelcast & mancenter or individually

question: Is there any way to deploy mancenter alone?

https://github.com/hazelcast/charts/issues/167

Cannot start only management service

https://github.com/hazelcast/charts/issues/161

2020-10-28 13:37 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2020-10-28 13:57 UTC, hasancelik requested changes
@jisnardo,

Could you bump up chart version of `hazelcast` and `hazelcast-enterprise`?

2020-10-28 14:03 UTC, hasancelik commented
verify

2020-10-28 15:02 UTC, hasancelik requested changes
@jisnardo,

I have added some minor comments, PTAL

2020-10-28 15:02 UTC, hasancelik commented on stable/hazelcast-enterprise/templates/metrics-service.yaml
> +{{- if and (.Values.hazelcast.enabled .Values.metrics.enabled) }}
```suggestion
{{- if and .Values.hazelcast.enabled .Values.metrics.enabled }}
```
PR builder failed due to below lint error:
```
17:03:43 ==> Linting stable/hazelcast-enterprise
17:03:43 [ERROR] templates/: template: hazelcast-enterprise/templates/metrics-service.yaml:1:19: executing "hazelcast-enterprise/templates/metrics-service.yaml" at <.Values.hazelcast.enabled>: enabled is not a method but has arguments
```
I think above change will make green our PR builder.

Also Could you apply same change to https://github.com/hazelcast/charts/blob/master/stable/hazelcast/templates/metrics-service.yaml?

2020-10-28 15:06 UTC, hasancelik commented
@jisnardo, could you update parameter table at READMEs? 
https://github.com/hazelcast/charts/tree/master/stable/hazelcast#configuration
https://github.com/hazelcast/charts/tree/master/stable/hazelcast-enterprise#configuration

2020-10-28 15:18 UTC, hasancelik commented
verify

2020-10-28 21:22 UTC, hasancelik approved these changes
LGTM 👍

2020-10-29 08:46 UTC, leszko reviewed
@jisnardo Thanks a lot or the PR 👍 

It looks good. Just one comment, could you add the condition `{{- if .Values.hazelcast.enabled -}}` also to `NOTES.txt`?

2020-10-29 09:21 UTC, jisnardo commented
> @jisnardo Thanks a lot or the PR +1
> 
> It looks good. Just one comment, could you add the condition `{{- if .Values.hazelcast.enabled -}}` also to `NOTES.txt`?

Just added.

2020-10-29 09:38 UTC, leszko approved these changes
@jisnardo thanks for the update. LGTM 👍

2020-10-29 09:38 UTC, merged