[CN-159] cluster connection
hazelcast/charts pull request #258
Opened 2021-11-11 11:18 UTC by SeriyBg

Add flag for switching cluster config creation on and off with default value set to `true`

2021-11-11 13:29 UTC, hasancelik requested changes

2021-11-11 13:29 UTC, hasancelik commented on stable/hazelcast-enterprise/values.yaml
> +    enabled: true
`clusterConfigCreation` is a little bit longer, I think. Also we should follow the same convention with other parameters like `service` , `serviceAccount` and `rbac`:
https://github.com/hazelcast/charts/blob/master/stable/hazelcast/values.yaml#L146
https://github.com/hazelcast/charts/blob/master/stable/hazelcast/values.yaml#L172
https://github.com/hazelcast/charts/blob/master/stable/hazelcast/values.yaml#L167
```suggestion
  clusterConfig:
    create: true
```

2021-11-12 06:43 UTC, hasancelik approved these changes
LGTM, thanks for the PR 👍

2021-11-12 10:06 UTC, alparslanavci approved these changes
Added a small comment, otherwise LGTM 👍

2021-11-12 10:19 UTC, SeriyBg commented on stable/hazelcast/README.md
> +| mancenter.clusterConfig.create|Cluster config creation will create the connection to the Hazelcast cluster based on the yaml.hazelcast-client|true|
I've meant the parameter in the helm chart `yaml: hazelcast-client`, but seems that it causes confusion. But now I see that in other places it's called mentioned as `hazelcast-client.yaml`, so have changed it accordingly

2021-11-12 11:13 UTC, merged