create pod disruption budget template
hazelcast/charts pull request #287
Opened 2022-07-25 09:12 UTC by SemihBKGR

# TODO
- add comment for new fields in values.yaml
- update table in README.md
- apply same changes for hazelcast-enterprise

2022-07-27 09:57 UTC, hasancelik requested changes

2022-07-27 10:06 UTC, mtyazici commented
@SemihBKGR, can you also increase the Chart version by looking at the current version in the master branch. Right now the updated one is the same as the master one.

2022-07-27 16:23 UTC, mtyazici approved these changes
I am OK with both of the option we talked offline. Maybe if you use the current options, we should comment about using Helm version greater than 3.7 for using PodDistruptionBudget.

2022-08-01 08:57 UTC, hasancelik approved these changes

2022-08-01 08:59 UTC, merged