Adapt helm chart for persistence improvements in 5.2
hazelcast/charts pull request #310
Opened 2022-10-17 08:05 UTC by vbekiaris

When hotRestart is enabled:
- Use /hazelcast/health/ready readiness probe to allow for proper cluster-wide recovery from persistence
- Allow watch verb on statefulsets resources, so Hazelcast can monitor statefulset spec & status changes and make informed decisions about member/cluster shutdown and startup
- Reduce default stale join timeout from 30 to 5 seconds, so rescheduled pods can rejoin the cluster without trouble

2022-10-17 09:46 UTC, hasancelik commented
@vbekiaris Could you bump up the chart version?
https://github.com/hazelcast/charts/blob/master/stable/hazelcast-enterprise/Chart.yaml#L3

2022-10-17 09:46 UTC, hasancelik approved these changes

2022-10-19 16:22 UTC, vbekiaris commented
> @vbekiaris Could you bump up the chart version?
> https://github.com/hazelcast/charts/blob/master/stable/hazelcast-enterprise/Chart.yaml#L3

done in 7e4e3ad

2022-10-31 09:52 UTC, hasancelik requested changes
@vbekiaris Could you bump up the chart version to `5.2.1`?

2022-10-31 09:58 UTC, hasancelik approved these changes

2022-10-31 10:11 UTC, merged