Add service.loadBalancerIP in order to set static IP
hazelcast/charts pull request #315
Opened 2022-10-19 20:19 UTC by itscaro

2022-10-24 10:43 UTC, mtyazici commented
Thanks for the PR @itscaro, could you also update the README files for both OS and EE charts?

2022-10-24 17:38 UTC, itscaro commented
@mtyazici I've updated README as well, thanks for the reminder

2022-10-25 08:27 UTC, mtyazici requested changes
Thanks for the PR

2022-10-25 08:27 UTC, mtyazici commented on stable/hazelcast-enterprise/templates/service.yaml
> +  {{- if (and (eq .Values.service.type "LoadBalancer") (.Values.service.loadBalancerIP) }}
```suggestion
  {{- if (and (eq .Values.service.type "LoadBalancer") (.Values.service.loadBalancerIP)) }}
```

2022-10-25 08:27 UTC, mtyazici commented on stable/hazelcast/templates/service.yaml
> +  {{- if (and (eq .Values.service.type "LoadBalancer") (.Values.service.loadBalancerIP) }}
```suggestion
  {{- if (and (eq .Values.service.type "LoadBalancer") (.Values.service.loadBalancerIP)) }}
```

2022-10-25 08:44 UTC, itscaro commented
@mtyazici Thanks for your review, good catch :)

2022-10-26 07:24 UTC, mtyazici approved these changes

2022-10-26 08:16 UTC, SeriyBg approved these changes

2022-10-26 15:49 UTC, merged