Update readinessProbe README value
hazelcast/charts pull request #322
Opened 2022-10-31 13:55 UTC by SeriyBg

2022-11-01 07:22 UTC, hasancelik requested changes

2022-11-01 07:22 UTC, hasancelik commented on stable/hazelcast/README.md
> -| readinessProbe.path | URL path that will be called to check readiness.| /hazelcast/health/node-state|
Actually, OS one still uses `/node-state`, we did not touch this one:
https://github.com/hazelcast/charts/commit/af6a41fac9429eebaccf5cc8fbb202617be06b21

2022-11-01 07:22 UTC, hasancelik commented on stable/hazelcast-enterprise/README.md
> -|readinessProbe.path|URL path that will be called to check readiness.|/hazelcast/health/node-state|
If persistence is not enabled, still chart uses `node-state` so we should mention in here

2022-11-01 07:22 UTC, hasancelik commented on stable/hazelcast/Chart.yaml
> -version: 5.5.0
README updates do not require bumping up the chart version

2022-11-01 08:39 UTC, SeriyBg commented on stable/hazelcast/README.md
> -| readinessProbe.path | URL path that will be called to check readiness.| /hazelcast/health/node-state|
But why does it use the `/node-state` one? The issue is related to the Persistence feature, an enterprise one. So the `ready` endpoint should be safe to be used with the `OS` version, isn't it?

2022-11-01 08:40 UTC, SeriyBg commented on stable/hazelcast-enterprise/README.md
> -|readinessProbe.path|URL path that will be called to check readiness.|/hazelcast/health/node-state|
But why do we need to use `node-state` and not always the `ready` endpoint?

2022-11-24 14:27 UTC, hasancelik commented on stable/hazelcast-enterprise/README.md
> -|readinessProbe.path|URL path that will be called to check readiness.|/hazelcast/health/node-state|
I do not know; we should check with the Core team. @vbekiaris put a condition for that at this PR:
https://github.com/hazelcast/charts/pull/310/files#diff-fd4e07be6999e034afbdbdbdaa8895afe76f634339c11a50e5cb715273d5ee65R123

2022-11-25 13:18 UTC, SeriyBg commented on stable/hazelcast-enterprise/README.md
> -|readinessProbe.path|URL path that will be called to check readiness.|/hazelcast/health/node-state|
You are right, will revert this change

2022-11-28 08:42 UTC, hasancelik approved these changes

2022-11-28 10:38 UTC, cagric0 approved these changes

2022-12-01 11:17 UTC, cagric0 approved these changes

2022-12-02 06:53 UTC, hasancelik requested changes

2022-12-02 10:01 UTC, SeriyBg commented on stable/hazelcast/Chart.yaml
> -version: 5.5.0
Done

2022-12-02 11:01 UTC, hasancelik approved these changes

2022-12-02 11:08 UTC, merged